# Made with ❤️ by binhnlt
version: '3'

services:
  webserver:
    build:
      context: .docker
      dockerfile: webserver.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - 8000:8000
      - 5173:5173
    volumes:
      - ./src:/app
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USERNAME=${DB_USERNAME:-laravel}
      - DB_PASSWORD=${DB_PASSWORD:-laravel}
      - DB_DATABASE=${DB_DATABASE:-laravel}
    depends_on:
      - database
      - redis

  database:
    image: docker.io/bitnami/mariadb:latest
    ports:
      - 33060:3306
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=${DB_USERNAME:-laravel}
      - MARIADB_PASSWORD=${DB_PASSWORD:-laravel}
      - MARIADB_DATABASE=${DB_DATABASE:-laravel}

  redis:
    image: redis:alpine

  mailpit:
    image: axllent/mailpit
    ports:
      - 8025:8025
